# Header
menu:
  Home: https://about.me/ivan_wei
  Blog: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- archive
- tag
- link
- category
# - tagcloud
# - recent_posts

# Miscellaneous
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
