# 头部菜单，title: link
menu:
    Facebook: https://fb.me/iivanwei
    Twitter: https://twitter.com/iivan_wei
    # 分類: /categories
    # 標簽: /tags
    # 封存: /archives
    # 關於: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - /music/See_You_On_The_Otherside_The_126ers.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  # - /img/cover.jpg
  - /img/welcome-cover.jpg

# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: https://fb.me/iivanwei
    twitter: https://twitter.com/iivan_wei
    github: https://github.com/IvanWei
    #wechat: /img/logo.png
    email: mailto:blog-contact@ivanwei.co
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link:

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: 'blog'
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords:
    - Web
    - JavaScript
    - JS
    - Nodejs
    - 開發
    - Development

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: G-PTEVL7FF0X

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
