name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Setup User Information
        run: |
          git config --global user.email "ivanwei_slack@outlook.com"
          git config --global user.name "WorldEarthBot"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Hexojs and packages
        run: |
          npm install -g hexo
          yarn install

      - name: Deployment
        run: npm run deploy
